version: '3.8'

services:
  # mongo:
  #   image: mongo:5
  #   restart: unless-stopped
  #   volumes:
  #     - mongo-data:/data/db

  auth:
    build:
      context: ../auth-service
    env_file:
      - ../auth-service/.env
    ports:
      - '4000:4000'
    # depends_on:
    #   - mongo
    restart: unless-stopped

  user:
    build:
      context: ../user-service
    env_file:
      - ../user-service/.env
    ports:
      - '4001:4001'
    depends_on:
      - auth
      # - mongo
    restart: unless-stopped

  post:
    build:
      context: ../post-service
    env_file:
      - ../post-service/.env
    ports:
      - '4002:4002'
    depends_on:
      - auth
      - user
      # - mongo
    restart: unless-stopped
  notification:
    build:
      context: ../notification-service
    env_file:
      - ../notification-service/.env
    ports:
      - '4003:4003'
    # depends_on:
    #   # - mongo
    restart: unless-stopped

volumes:
  mongo-data:
