version: '3.8'

services:
  user:
    build:
      context: ../user-service
    env_file:
      - ../user-service/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  post:
    build:
      context: ../post-service
    env_file:
      - ../post-service/.env
    ports:
      - "4001:4001"
    depends_on:
      - user
    restart: unless-stopped

  notification:
    build:
      context: ../notification-service
    env_file:
      - ../notification-service/.env
    ports:
      - "4002:4002"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - user
      - post
      - notification
    restart: unless-stopped
