apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
  - port: 4002
    targetPort: 4002
    protocol: TCP
    nodePort: 30004
