apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: post-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4001
        env:
        - name: MONGO_URI
          value: "mongodb+srv://admin:12345@cluster0.eghvz.mongodb.net/postdb?retryWrites=true&w=majority"
        - name: USER_URL
          value: "http://user-service:4000"
        - name: NOTIF_URL
          value: "http://notification-service:4002"
        readinessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4001
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
