apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: post-service
  type: NodePort
  ports:
  - port: 4001
    targetPort: 4001
    protocol: TCP
    nodePort: 30003
