apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: "mongodb+srv://admin:12345@cluster0.eghvz.mongodb.net/userdb?retryWrites=true&w=majority"
        - name: JWT_SECRET
          value: "supersecretkey"
        - name: JWT_EXPIRES_IN
          value: "15m"
        - name: REFRESH_TOKEN_EXPIRES_IN
          value: "7d"
        - name: NOTIF_URL
          value: "http://notification-service:4002"
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
